package com.example.hospital.enums;

public enum Specialist {
    CARDIOLOGIE,
    DERMATOLOGIE,
    GASTROENTEROLOGIE,
    NEUROLOGIE,
    OPHTALMOLOGIE,
    ORL, // Oto-Rhino-Laryngologie
    PEDIATRIE,
    GYNECOLOGIE,
    ORTHOPEDIE,
    PSYCHIATRIE,
    RADIOLOGIE,
    CHIRURGIE_GENERALE,
    CHIRURGIE_CARDIAQUE,
    CHIRURGIE_ORTHOPEDIQUE,
    ANESTHESIOLOGIE,
    UROLOGIE,
    ENDOCRINOLOGIE,
    ONCOLOGIE,
    MEDECINE_GENERALE,
    MEDECINE_INTERNE,
    NEPHROLOGIE,
    RHEUMATOLOGIE,
    INFECTIOLOGIE
}
